version: "3.3"

services:
  deno:
    image: "deno-docker:0.0.1"
    build: .
    ports:
      - "81:8081"
      - "82:8082"
    networks:
      lcom:
          aliases:
            - ctt-server.loicroux.com
    labels:
            - "traefik.enable=true"
            - "traefik.backend=ctt_server"
            - "traefik.frontend.rule=Host:ctt-server.loicroux.com"
            - "traefik.port=80"
            - "traefik.backend.loadbalancer.method=wrr"
            - "traefik.backend.loadbalancer.sticky=false"
            - "traefik.protocol=http"
            - "traefik.weight=10"

networks:
    lcom:
        external: true
