version: "3.3"

services:
  ctt:
    restart: always
    image: "deno-ctt:0.0.1"
    build: .
    ports:
      - "81:8081"
    networks:
      - lcom
    labels:
            - "traefik.enable=true"
            - "traefik.backend=ctt_server"
            - "traefik.frontend.rule=Host:ctt-server.loicroux.com"
            - "traefik.port=81"
            - "traefik.backend.loadbalancer.method=wrr"
            - "traefik.backend.loadbalancer.sticky=false"
            - "traefik.protocol=http"
            - "traefik.weight=10"
  ws:
    restart: always
    image: "deno-ws:0.0.1"
    build: 
      context: .
      dockerfile: Dockerfile.ws
    networks:
      - lcom
    ports:
      - "82:8082"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ctt_server"
      - "traefik.frontend.rule=Host:ws.ctt-server.loicroux.com"
      - "traefik.port=82"
      - "traefik.backend.loadbalancer.method=wrr"
      - "traefik.backend.loadbalancer.sticky=false"
      - "traefik.protocol=http"
      - "traefik.weight=10"

networks:
    lcom:
        external: true
