name: deploy

on:
  push:
    branches:
      - master
      #- develop

jobs:
  build:
    env:
      CI: true
      TOKEN: ${{ secrets.TOKEN}} # Always data token to deploy website
      CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
      CI_USER_PAT: ${{ secrets.CI_USER_PAT }}
      DENO_INSTALL: '/Users/runner/.local'

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x

      - run: timeout 15 make start

      - name: deploy after last check
        run: make deploy-ald
