name: test

on: [pull_request]

jobs:
  build:
    env:
      DENO_INSTALL: '/Users/runner/.local'
    name: Ctt-server in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x

      - name: unit tests
        run: |
          export PATH=$DENO_INSTALL/bin:$PATH
          make test

      - name: deno format check
        run: |
          export PATH=$DENO_INSTALL/bin:$PATH
          deno fmt --check
