name: test

on: [pull_request]

jobs:
  build:
    env:
      DENO_INSTALL: "/Users/runner/.local"
    name: Ctt-server in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x

      - name: Test server
        run: |
          timeout 15 make start

      # TODO: fix after deno patch
      # - name: Tests E2E and units
      #   run: |
      #     make tests

      - name: deno format check
        run: |
          deno fmt --check

