name: test

on: [pull_request]

jobs:
  build:
    env:
      DENO_INSTALL: "/Users/runner/.local"
      PATH: $DENO_INSTALL/bin:$PATH
    name: Ctt-server in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x

      - name: Tests
        run: |
          make tests

      - name: deno format check
        run: |
          deno fmt --check

# TODO : e2e tests
