name: test

on: [pull_request]

jobs:
  build:
    env:
      DENO_INSTALL: "/Users/runner/.local"
    name: Ctt-server in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x

      - name: Create date cache identifier
        id: date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y_w%V")"
        shell: bash

      - uses: actions/cache@v2
        id: deno-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ env.DENO_INSTALL }}
          key: ${{ runner.os }}-deno
          restore-keys: |
            ${{ runner.os }}-deno-${{ steps.date.outputs.date }}

      - name: Test server
        run: |
          timeout 60 make start

      # TODO: fix after deno patch
      # - name: Tests E2E and units
      #   run: |
      #     make tests

      - name: deno format check
        run: |
          deno fmt --check

